services:
  - type: web
    name: calculator-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -e . && pytest
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DATABASE_URL
        value: ${postgres.PG_URL}
    repo: https://github.com/0NSingh/calculator-app.git

  - type: pserv
    name: calculator-db
    plan: free
    rootDir: .
    repo: https://github.com/0NSingh/calculator-app.git